/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file
         * @description Returns the file content as a binary stream.
         *     If the path ends with `/`, returns a directory listing instead.
         */
        get: operations["downloadFile"];
        /**
         * Upload a file
         * @description Upload a file to the given path. If the path ends with `/` and the
         *     body is empty, a directory is created instead (prefer `/files-mkdir`
         *     for that intent).
         */
        put: operations["uploadFile"];
        post?: never;
        /**
         * Delete a file
         * @description Soft-deletes a file or directory (moves to trash).
         */
        delete: operations["deleteFile"];
        options?: never;
        /**
         * Get file metadata
         * @description Returns Content-Length, Content-Type, and ETag headers without the body.
         */
        head: operations["headFile"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files in a directory
         * @description Returns the files and directories at the root of the token's base path.
         *     For a subdirectory, use `downloadFile` with a trailing slash.
         */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files-move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move or rename a file/directory
         * @description Moves or renames a file or directory. Both source and destination
         *     paths are in the JSON body.
         *
         *     Overwrite semantics mirror WebDAV `MOVE Overwrite:T`:
         *       * `overwrite=false` (default): a destination collision returns 412
         *         Precondition Failed.
         *       * `overwrite=true`: an existing destination *file* is replaced
         *         (destination node identity and version history are preserved; the
         *         source is then soft-deleted). A directory destination, or a
         *         source/destination type mismatch, returns 409.
         *
         *     Moving a directory into its own subtree returns 409.
         */
        post: operations["moveFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files-copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a file or directory
         * @description Copies a file or directory.
         *
         *     Response shape is discriminated by the source type (see the
         *     `oneOf` on the 201 response):
         *
         *       * `type: "file"` — single-file copy. Returns the new node's id,
         *         size, hash, and content_version.
         *       * `type: "directory"` — recursive subtree copy. Returns one entry
         *         per file/directory copied. Directory entries omit size/hash.
         *
         *     Overwrite semantics for directory copy are **history-preserving**:
         *     when `overwrite=true` and a destination file already exists at a
         *     path inside the subtree, the existing node is kept and a new
         *     revision is appended. The destination's version
         *     history is preserved. Existing destination files that do not
         *     collide with source paths are left untouched (merge semantics).
         *
         *     **Non-atomic contract for directory copy**: the walk is performed
         *     as a sequence of per-entry writes. On failure mid-walk, already-
         *     copied entries are not rolled back; the error response includes a
         *     `partial` flag and the list of entries that did succeed so clients
         *     can resume or reconcile.
         */
        post: operations["copyFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files-mkdir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a directory
         * @description Creates a directory at the given path. REST counterpart to WebDAV MKCOL.
         *     Idempotent: if the path already exists as a
         *     directory, returns 200 with the existing node; if it exists as a file,
         *     returns 409.
         */
        post: operations["mkdir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token introspection (Bearer-only)
         * @description Returns information about the calling Bearer token. Cookie sessions
         *     receive 403 — the WebUI uses `/internal/account` for equivalent context.
         */
        get: operations["getToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an API token
         * @description Create a new scoped API token with auto-issue. Returns the raw token
         *     string (shown once only) along with the token metadata.
         *
         *     With a Bearer token (must have `can_delegate: true`), the new token
         *     becomes a child token whose scope is a subset of the caller's. With a
         *     cookie session, the new token is created at the user root.
         *
         *     Listing user tokens and metadata edits live at `/internal/tokens` (cookie-only).
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an API token
         * @description Delete an API token. With a cookie session, deletes any owned token.
         *     With a Bearer token, only direct child tokens created via delegation
         *     (origin_id must match the caller's token ID) can be deleted.
         *
         *     If the token still has delegation children (other tokens reference
         *     it via parent_grant_id), the delete is rejected with 409
         *     `has_children` — the children must be deleted (or detached) first.
         */
        delete: operations["deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a chunked upload session
         * @description Create an upload session for large files. Upload the chunks, then call
         *     complete to finalize.
         */
        post: operations["createUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/{chunk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload a chunk
         * @description Upload a single chunk of a file. Every chunk except the last must be exactly the session chunk size.
         */
        put: operations["uploadChunk"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an upload session
         * @description Finalize the upload session and commit the file.
         */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel an upload session */
        delete: operations["cancelUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Machine-readable error code
                 * @example not_found
                 * @example unauthorized
                 * @example forbidden
                 * @example validation_error
                 */
                code: string;
                /** @description Human-readable error message */
                message: string;
            };
        };
        AccessPath: {
            /**
             * @description Path relative to the token's `base_path`.
             *     - `""` (empty string) is the canonical root and grants access to
             *       everything under `base_path`.
             *     - Subpaths are relative: `"photos"`, `"projects/myapp/src"`. No
             *       leading `/`. A trailing `/` is stripped on receipt.
             *     `.` / `..` segments, consecutive slashes, NUL bytes, newlines, and
             *     leading/trailing whitespace are rejected.
             */
            path: string;
            /**
             * @description Access level for this path. Cumulative: "write" implies "read".
             *     - read: list, download, metadata
             *     - write: read + create, update, delete
             * @enum {string}
             */
            access: "read" | "write";
        };
        FileItem: components["schemas"]["FileItemFile"] | components["schemas"]["FileItemDirectory"];
        FileItemFile: {
            id: string;
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            size: number;
            /** Format: date-time */
            modified_at: string;
            hash?: string | null;
            revision_id?: string | null;
            /** @description Monotonic version counter (CAS token). */
            content_version: number;
            content_type: string;
        };
        FileItemDirectory: {
            id: string;
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "directory";
            /** @description Always null for directories. */
            hash?: string | null;
            /** @description Always null for directories. */
            revision_id?: string | null;
            /** @description Monotonic version counter (CAS token). */
            content_version: number;
            content_type: string;
        };
        UploadResult: {
            id: string;
            name: string;
            size: number;
            hash: string;
            /** @description Monotonic version counter (CAS token). */
            content_version: number;
        };
        CopyFileResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            id: string;
            size: number;
            hash: string;
            /** @description Monotonic version counter on the destination node (CAS token). */
            content_version: number;
        };
        CopyTreeEntry: {
            /** @constant */
            kind: "file";
            src_path: string;
            dest_path: string;
            id: string;
            size: number;
            hash: string;
            content_version: number;
            /** @description True when the destination file already existed and a new revision was appended (history-preserving). */
            existed: boolean;
        } | {
            /** @constant */
            kind: "directory";
            src_path: string;
            dest_path: string;
            id: string;
            /** @description True when the destination directory already existed and entries were merged into it. */
            existed: boolean;
        };
        CopyTreeResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "directory";
            /**
             * @description One entry per file or directory copied. Non-atomic: on partial
             *     failure, this list reflects only the entries that succeeded
             *     before the error.
             */
            entries: components["schemas"]["CopyTreeEntry"][];
        };
        CopyTreeError: {
            error: {
                code: string;
                message: string;
                /**
                 * @description True iff at least one entry was written before the failure
                 *     (directory copy is non-atomic — already-copied entries
                 *     remain on the server).
                 */
                partial?: boolean;
                failed_at_src?: string | null;
                failed_at_dest?: string | null;
            };
            /** @description Entries successfully copied before the failure (directory copy only). */
            entries?: components["schemas"]["CopyTreeEntry"][];
        };
        MkdirResult: {
            id: string;
            name: string;
            /** @constant */
            type: "directory";
        };
        ApiToken: {
            id: string;
            name: string;
            base_path: string;
            can_delegate: boolean;
            /** @description Parent token ID if created via delegation. */
            origin_id: string | null;
            /** Format: date-time */
            created_at: string;
            access_paths: components["schemas"]["AccessPath"][];
        };
        /**
         * @description Token holders cannot learn the absolute position of their `base_path`
         *     within the delegator's tree. All paths in API responses (including
         *     `access_paths` below) are relative to the token's base_path.
         */
        TokenIntrospection: {
            user_id: string;
            token_id: string;
            can_delegate: boolean;
            access_paths: components["schemas"]["AccessPath"][];
        };
    };
    responses: {
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description File path relative to the token's base path.
         *     Can contain slashes for nested paths (e.g. `docs/readme.txt`).
         */
        FilePath: string;
        /**
         * @description Quoted content version for optimistic locking (e.g. `"5"`).
         *     The request succeeds only if the current version matches.
         */
        IfMatch: string;
        /**
         * @description Set to `*` to succeed only if the resource does not exist.
         *     For GET/HEAD, set to an ETag value to get 304 if unchanged.
         */
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted content version integer (e.g. `"5"`). Use with `If-Match` for optimistic locking. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    downloadFile: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Set to `*` to succeed only if the resource does not exist.
                 *     For GET/HEAD, set to an ETag value to get 304 if unchanged.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /**
                 * @description File path relative to the token's base path.
                 *     Can contain slashes for nested paths (e.g. `docs/readme.txt`).
                 */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not modified (ETag match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Quoted content version for optimistic locking (e.g. `"5"`).
                 *     The request succeeds only if the current version matches.
                 */
                "If-Match"?: components["parameters"]["IfMatch"];
                /**
                 * @description Set to `*` to succeed only if the resource does not exist.
                 *     For GET/HEAD, set to an ETag value to get 304 if unchanged.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /**
                 * @description File path relative to the token's base path.
                 *     Can contain slashes for nested paths (e.g. `docs/readme.txt`).
                 */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description File uploaded successfully */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Precondition failed (If-Match / If-None-Match) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Storage limit exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description File path relative to the token's base path.
                 *     Can contain slashes for nested paths (e.g. `docs/readme.txt`).
                 */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    headFile: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Set to `*` to succeed only if the resource does not exist.
                 *     For GET/HEAD, set to an ETag value to get 304 if unchanged.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /**
                 * @description File path relative to the token's base path.
                 *     Can contain slashes for nested paths (e.g. `docs/readme.txt`).
                 */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File metadata in headers */
            200: {
                headers: {
                    "Content-Length"?: number;
                    "Content-Type"?: string;
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified (ETag match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["FileItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    moveFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Source path (relative to token's base path). */
                    from: string;
                    /** @description Destination path (relative to token's base path). */
                    to: string;
                    /**
                     * @description When true, replace an existing destination *file* in
                     *     place (preserves the destination's version history).
                     * @default false
                     */
                    overwrite?: boolean;
                };
            };
        };
        responses: {
            /** @description File moved or replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Node ID of the moved (or replaced) file. */
                        id: string;
                        /** @description Monotonic version counter (CAS token). */
                        content_version: number;
                        /** @description Present and true when the response describes a replace (overwrite=true and the destination already existed). */
                        overwritten?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description Cycle detected (descendant move) or destination type mismatch
             *     (e.g. overwrite=true with directory destination).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Destination already exists and overwrite is false */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    copyFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Source path (relative to token's base path). */
                    from: string;
                    /** @description Destination path (relative to token's base path). */
                    to: string;
                    /**
                     * @description When true, overwrite the destination if it exists.
                     *     For directory copy, this triggers the history-preserving
                     *     merge described above.
                     * @default false
                     */
                    overwrite?: boolean;
                };
            };
        };
        responses: {
            /** @description Source copied */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyFileResult"] | components["schemas"]["CopyTreeResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description Destination already exists (overwrite=false), type mismatch
             *     between source and destination, or cycle (destination inside
             *     source subtree). For directory copy, the body includes a
             *     `partial` flag and the list of entries successfully copied
             *     before the failure.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyTreeError"];
                };
            };
            /** @description Storage limit exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyTreeError"];
                };
            };
        };
    };
    mkdir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Directory path (relative to token's base path). */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Directory already exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MkdirResult"];
                };
            };
            /** @description Directory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MkdirResult"];
                };
            };
            /** @description Invalid path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Path already exists as a file */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token introspection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenIntrospection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Display name for the token. */
                    name: string;
                    /**
                     * @description Root path for the token's scope.
                     * @default /
                     */
                    base_path?: string;
                    /**
                     * @description Whether this token can create child tokens.
                     * @default false
                     */
                    can_delegate?: boolean;
                    /**
                     * @description Token expiry in days from creation.
                     * @default 90
                     */
                    expires_in_days?: number;
                    access_paths: components["schemas"]["AccessPath"][];
                };
            };
        };
        responses: {
            /** @description Token created and issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: components["schemas"]["ApiToken"];
                        /** @description The raw s2_ token string. Shown once only. */
                        raw_token: string;
                        /**
                         * Format: date-time
                         * @description Token expiration timestamp.
                         */
                        expires_at: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Token has delegation children; delete or detach them first */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Destination file path. */
                    path: string;
                    /** @description Total file size in bytes (required). Server computes expected chunk count from this. */
                    totalSize: number;
                };
            };
        };
        responses: {
            /** @description Upload session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessionId: string;
                        nodeId: string;
                        /** @description Maximum chunk size in bytes (4 MB). */
                        chunkSize: number;
                        /** Format: date-time */
                        expiresAt: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Storage limit exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                id: string;
                /** @description Zero-based chunk index */
                chunk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Chunk uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodeId: string;
                        size: number;
                        chunkCount: number;
                        /** @description Monotonic version counter (CAS token). */
                        content_version: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Upload session conflict (missing chunks or already completed) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload session cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
