export interface ListItem {
  key: string;
}

export interface StorageObject {
  body: ReadableStream;
}

interface StorageHead {
  size: number;
}

/**
 * Storage keys are slash-separated opaque object keys generated by the server.
 * A key must not be a path-prefix of another key; filesystem-backed storage
 * maps each key to one file.
 */
export interface StorageAdapter {
  /**
   * Physical backend capacity, when the backend exposes meaningful filesystem
   * statistics. This is separate from each user's logical quota usage.
   */
  availableBytes(): Promise<number | null>;
  get(key: string): Promise<StorageObject | null>;
  head(key: string): Promise<StorageHead | null>;
  put(key: string, body: ArrayBuffer): Promise<void>;
  delete(key: string): Promise<void>;
  /**
   * Delete many keys in one round-trip when the backend supports it (e.g. S3-style
   * APIs take up to 1000 keys per call). Implementations are free to fall back to a
   * sequential per-key loop. No-op on empty input.
   */
  deleteMany(keys: string[]): Promise<void>;
  list(prefix: string): Promise<ListItem[]>;
}

export function validateStorageKey(key: string): string[] {
  if (key.length === 0 || key.startsWith("/") || key.includes("\\")) {
    throw new Error(`Invalid storage key: ${key}`);
  }
  const segments = key.split("/");
  if (
    segments.some(
      (segment) =>
        segment === "" ||
        segment === "." ||
        segment === ".." ||
        segment.startsWith("."),
    )
  ) {
    throw new Error(`Invalid storage key: ${key}`);
  }
  return segments;
}

export function validateStoragePrefix(prefix: string): string[] {
  if (!prefix.endsWith("/")) {
    throw new Error(`Invalid storage prefix: ${prefix}`);
  }
  return validateStorageKey(prefix.slice(0, -1));
}
